import axios from 'axios';
const API_BASE_URL = 'https://my-portfolio-api-euq5.onrender.com/api/v1';

// Create an Axios instance
const api = axios.create({
    baseURL: API_BASE_URL,
    withCredentials: true,
});

export const loginAdmin = async (password) => {
    try {
        const response = await api.post('/auth/login', { password });
        return response.data; // Should return success: true
    } catch (error) {
        // Use optional chaining to safely access response status and data
        throw new Error(error.response?.data?.message || 'Login failed due to network error.');
    }
};

// --- DailyWork Log Service ---

// GET: Fetch logs (Public access)
export const getDailyLogs = async (limit = 6, skip = 0) => {
    try {
        const response = await api.get(`/worklog/alltask`);
        return response.data; // Contains data, count, totalLogs
    } catch (error) {
        console.error("Error fetching daily logs:", error);
        return { data: [], totalLogs: 0 }; // Return empty data on failure
    }
};

// POST: Add a new task (Protected access)
export const addTask = async (title) => {
    try {
        // The dateString is generated by the server now, so we only send the title
        const response = await api.post('/worklog/createtask', { title });
        return response.data.data; // Returns the updated DayLog object
    } catch (error) {
        // The server will return 401/403 if unauthorized or expired
        throw new Error(error.response?.data?.error || 'Failed to add task.');
    }
};

// PATCH: Update progress (Protected access)
export const updateTaskProgress = async (dayId, taskId, progress) => {
    try {
        const response = await api.patch(`/worklog/task/${dayId}/${taskId}`, { progress });
        return response.data.data; // Returns the updated DayLog object
    } catch (error) {
        throw new Error(error.response?.data?.error || 'Failed to update progress.');
    }
};

